name: Deployment
on:
  workflow_call:
    inputs:
      os-version:
        description: "Runner OS"
        required: false
        type: array
        default: [ ubuntu-latest ]
    outputs:
      results:
        value: ${{jobs.deploy.outputs.page_url}}
jobs:
  deploy:
    outputs:
      page_url: ${{ steps.deploy-id.outputs.page_url }}

    strategy:
      matrix:
        os: ${{ inputs.os-version }}
    runs-on: ${{ matrix.os }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-id.outputs.page_url }}

    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: deploy artifact to Github pages
        id: deploy-id
        uses: actions/deploy-pages@v4

      - name: Print deployment URL
        run: |
          echo "ðŸš€ Site deployed to: ${{ steps.deploy-id.outputs.page_url }}"