name: Football Tracker CI/CD

on:
  push:
    branches:
     - main
  pull_request:
  schedule:
    - cron: "0 2 * 12 *"


jobs:
  Test_code:
    strategy:
      matrix:
        node-version: [18,20]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    environment: football_tracker
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: install dependencies
        run: npm ci

      - name: linting
        run: npm run lint

      - name: run test
        run: |
          npx jest --json --outputFile=test-results.json 



      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ github.job }}-${{ runner.os }}-${{ matrix.node-version }}
          path: test-results.json


  run_server:
    runs-on: ubuntu-latest
    environment: football_tracker
    needs: Test_code
    env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}


    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: install dependencies
        run: npm ci

      - name: Debug MONGODB_URI presence
        run: |
          if [ -z "$MONGODB_URI" ]; then
            echo "‚ùå MONGODB_URI is empty"
            exit 1
          else
            echo "‚úÖ MONGODB_URI is loaded"
            echo "Length: ${#MONGODB_URI}"
          fi


      - name: Start server and call url
        run: |
          npm start & sleep 5
          curl -f http://localhost:3000/matches
  build:
    runs-on: ubuntu-latest
    needs: run_server
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: grant read permission
        run: chmod +x ./scripts/build.sh

      - name: cache artifact
        id: cached-artifact
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ hashFiles('frontend/**/*') }}

      - name: build artifact
        if: steps.cached-artifact.outputs.cache-hit != 'true'
        run: npm run build

      - name: upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist



  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-id.outputs.page_url }}

    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: deploy artifact to Github pages
        id: deploy-id
        uses: actions/deploy-pages@v4

      - name: Print deployment URL
        run: |
          echo "üöÄ Site deployed to: ${{ steps.deploy-id.outputs.page_url }}"

  Backup:
    environment: football_tracker
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install python dependencies
        run: |
          python3 -m pip install pymongo
          pip install python-dotenv

      - name: backup_code
        id: backup
        run: python3 backup.py

      - name: save time details
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "artifact_time=$TIMESTAMP-$SHORT_SHA" >> $GITHUB_ENV

      - name: upload backup Artifact
        id: backup_artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ env.artifact_time }}
          path: backup.json

      - name: backup failure report
        id: error-report
        if: ${{ failure() && (steps.backup.outcome == 'failure' || steps.backup_artifact.outcome == 'failure') }}
        run: |
          echo "the repo name: ${{ github.repository }}" >> log.txt
          echo "the branch name: ${{ github.ref_name }}" >> log.txt
          echo "the time: ${{ github.run_started_at }}" >> log.txt
          echo "Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> log.txt

      - name: upload error
        id: upload-error
        if: failure() && steps.error-report.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: error report-${{ env.artifact_time }}
          path: log.txt

      - name: send email if backup fails
        if: failure() && steps.upload-error.outcome == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "‚ö†Ô∏è Backup Failed for ${{ github.repository }}"
          to: ${{ secrets.EMAIL_TO }}
          from: "CI Bot <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Backup job failed for:
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: log.txt

      - name: send discord message if backup fails
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: failure() && steps.upload-error.outcome == 'success'
        run: |
          echo "Backup job failed for:" >> discord.txt
          echo "Repository: ${{ github.repository }}" >> discord.txt
          echo "Branch: ${{ github.ref_name }}" >> discord.txt
          echo "Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> discord.txt
          curl -H "Content-Type: application/json" \
                -X POST \
                -d "$(jq -n --arg content "$(cat discord.txt)" '{content: $content}')" \
                $DISCORD_WEBHOOK
        

        
  

  report:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: failure()
    steps:
      - name: Get report
        run: |
          echo " There is something wrong"
          echo "${{ toJson(github) }}"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs-${{ github.job }}-${{ runner.os }}-${{ matrix.node-version || 'NA' }}
          path: ${{ github.workspace }}




     
