name: Report
on: workflow_call

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate report file
        run: |
          echo "⚠️ There is something wrong" > log.txt
          echo '${{ toJson(github) }}' > log.json
          cat log.json | jq -r 'to_entries[] | "\(.key): \(.value.result)"' >> log.txt

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs-${{ github.job }}-${{ runner.os }}
          path: |
            log.txt
            
